# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvReaderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10)),
                ('component_id', models.CharField(max_length=50)),
                ('magic_name', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'csv_reader_info',
            },
        ),
        migrations.CreateModel(
            name='CsvReaderInfotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10)),
                ('component_id', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=10)),
                ('date_format', models.CharField(blank=True, max_length=20, null=True)),
                ('sample_data', models.CharField(max_length=1000)),
                ('selected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'csv_reader_infotype',
            },
        ),
    ]
