# 请求参数不存在
PARAMETER_MISSING_ERROR = "PARAMETER_MISSING_ERROR"
# 参数错误
PARAMETER_VALUE_ERROR = "PARAMETER_VALUE_ERROR"
#  改方法不支持GET
GET_DENIED_FOR_THIS_METHOD = "GET_DENIED_FOR_THIS_METHOD"
# 登陆失败
LOGIN_ERROR = "LOGIN_ERROR"
# 用户未登陆
NOT_LOGIN = "NOT_LOGIN"
# JAVA服务连接错误，可能是由于JAVA服务没有开启，请联系管理员
PY4J_CONNECTION_ERROR = "PY4J_CONNECTION_ERROR"
# 数据库连接失败
DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
# 已存在重名数据，请修改数据名称
DATA_NAME_HAS_BEEN_USED = "DATA_NAME_HAS_BEEN_USED"
# 超过最大上传大小
MY_DATA_UPLOAD_SIZE_EXCEED = "MY_DATA_UPLOAD_SIZE_EXCEED"

TARGET_FIELD_SELECT_ERROR = "所选变量要求为目标字段（数据只包含0或1,且0的数量大于1的数量）"

CSV_COLUMN_SIZE_ERROR="csv文件列数量太少"
CSV_COLUMN_NUM_ERROR="csv文件字段列数不匹配"
CSV_EMPTY="文件不能为空"
CSV_ROW_TOO_SMALL="csv文件数据太少"
CSV_UTF8_ERROR="文件编码错误"
NO_TARGET_FEILD="上传的文件没有Target字段"
TARGET_FIELD_ERROR="Target字段值不符合要求"

COMPONENT_NOT_EXIST="数据对象不存在"
CSV_SAVE_ERROR="csv信息报错失败"
DATA_IS_NORE = "数据为空"
CSV_READER_NOT_CONFIGURED = "CSV_READER_NOT_CONFIGURED"
# 不存在该算法或不支持
ALGORITHM_NOT_SUPPORTED = "不存在该算法或不支持"
CSV_TYPE_ERROR="组件类型错误"

# explore
EXPLORE_PARAM_ERROR = "参数类型值错误"

# learn
EMPTY_PARAM = "参数为空"
VALUE_ERROR_PARAM = "参数值出错"
ALGORITHM_PARAM_ERROR = "算法类型值错误"
SAVE_PARAM_ERROR = "算法配置操作失败"

ATOM_LEARN_NOT_CONFIGURED = "ATOM_LEARN_NOT_CONFIGURED"
INPUT_NOT_SAME_AS_LEARN = "INPUT_NOT_SAME_AS_LEARN"
COMPONENT_NOT_SAME_AS_LEARN = "COMPONENT_NOT_SAME_AS_LEARN"


# act
COMPONENT_NOT_SAME_AS_ACT = "COMPONENT_NOT_SAME_AS_ACT"
PARAMS_NOT_IS_NULL = "PARAMS_NOT_IS_NULL"
ATOM_ACT_NOT_CONFIGURED = "ATOM_ACT_NOT_CONFIGURED"

# test
ATOM_TEST_NOT_CONFIGURED = "ATOM_TEST_NOT_CONFIGURED"
# robot_x

# 组件ID不正确
COMPONENT_ID_ERROR = "component001"

# task
TASK_IS_EXECUTING = "TASK_IS_EXECUTING"
NO_SUCH_TASK = "NO_SUCH_TASK"
TASK_HAS_NO_LOG="TASK_HAS_NO_LOG"